 (
ID_NUMBER
FISCAL_YEAR ,
DEPARTMENT_NAME ,
VENDOR_NAME ,
TRANSACTION_DATE 
DOLLAR_AMOUNT
AUTHORITY  ,
BUSINESS_TAX_REGISTRATION_CERTIFICATE  ,
GOVERNMENT_ACTIVITY  ,
FUND_GROUP_NAME ,
FUND_TYPE ,
FUND_NAME ,
FUND ,
ACCOUNT_NAME  ,
ACCOUNT_CODE  ,
TRANSACTION_ID  ,
EXPENDITURE_TYPE  ,
SETTLEMENT_JUDGMENT  ,
FISCAL_MONTH_NUMBER ,
FISCAL_YEAR_MONTH ,
FISCAL_YEAR_QUARTER ,
CALENDAR_MONTH_NUMBER ,
CALENDAR_MONTH_YEAR  ,
CALENDAR_MONTH ,
DATA_SOURCE ,
AUTHORITY_NAME ,
AUTHORITY_LINK,
DEPARTMENT_NUMBER ,
PROGRAM ,
VENDOR_ID ,
ZIP  ,
PAYMENT_METHOD  ,
PAYMENT_STATUS  ,
INV_NUM 
INVOICE_DUE_DATE 
INVOICE_DISCOUNT_DUE_DATE 
INV_DATE 
INV_LINE
INVOICE_DISTRIBUTION_LINE
PO_NUM ,
DESCRIPTION ,
DETAILED_ITEM_DESCRIPTION ,
UNIT_PRICE
UNIT_OF_MEASURE  ,
QUANTITY
SALES_TAX_PERCENT
SALES_TAX
DISCOUNT
RECEIVER_ID  ,
PO_DATE 
PO_LINE_NUMBER
PROCUREMENT_ORGANIZATION  ,
BUYER_NAME  ,
SUPPLIER_CITY  ,
SUPPLIER_COUNTRY  ,
BU_NAME  ,
SITE_LOCATION  ,
ITEM_CODE  ,
ITEM_CODE_NAME  ,
CURRENCY  ,
VALUE_OF_SPEND
VENDOR_NUM
)